import type { ManuscriptRow } from './types'

export const CURRENT_JOURNAL = {
  name: 'UNILAG Journal of Engineering Research',
  abbreviation: 'UJER',
  slug: 'ujer',
  issnElectronic: '2971-0448',
}

export const OTHER_JOURNALS = [
  { name: 'UNILAG Journal of Environmental Studies', abbreviation: 'UJES', slug: 'ujes' },
  { name: 'Akoka Journal of Computing', abbreviation: 'AJC', slug: 'ajc' },
]

export const CURRENT_USER = {
  name: 'Dr. Adaeze Okonkwo',
  initials: 'AO',
  role: 'Handling editor · Civil & Structural',
}

/** Placeholder rows so the desk shows what it does before the database exists. */
export const MANUSCRIPTS: ManuscriptRow[] = [
  {
    id: 'm1',
    reference: 'UJER-2026-0147',
    title: 'Compressive Strength of Laterite-Cement Blocks Stabilised with Rice Husk Ash',
    section: 'Civil & Structural',
    status: 'decision_pending',
    correspondingAuthor: 'I. Balogun',
    authorCount: 4,
    handlingEditor: 'A. Okonkwo',
    round: 1,
    submittedAt: '2026-07-02',
    daysInStatus: 9,
    similarityPercent: 8,
    blinding: 'double_blind',
    hasOverdueReview: false,
    reviewers: [
      { id: 'r1', displayName: 'Reviewer 1', status: 'submitted', dueAt: '2026-08-14', recommendation: 'minor_revision' },
      { id: 'r2', displayName: 'Reviewer 2', status: 'submitted', dueAt: '2026-08-14', recommendation: 'major_revision' },
      { id: 'r3', displayName: 'Reviewer 3', status: 'declined', dueAt: '2026-08-14' },
    ],
  },
  {
    id: 'm2',
    reference: 'UJER-2026-0151',
    title: 'Short-Term Load Forecasting for the Lagos Distribution Network Using Gradient Boosting',
    section: 'Electrical & Electronics',
    status: 'under_review',
    correspondingAuthor: 'C. Eze',
    authorCount: 2,
    handlingEditor: 'A. Okonkwo',
    round: 1,
    submittedAt: '2026-07-19',
    daysInStatus: 31,
    similarityPercent: 14,
    blinding: 'double_blind',
    hasOverdueReview: true,
    reviewers: [
      { id: 'r4', displayName: 'Reviewer 1', status: 'submitted', dueAt: '2026-09-01', recommendation: 'accept' },
      { id: 'r5', displayName: 'Reviewer 2', status: 'accepted', dueAt: '2026-09-01' },
      { id: 'r6', displayName: 'Reviewer 3', status: 'invited', dueAt: '2026-09-11' },
    ],
  },
  {
    id: 'm3',
    reference: 'UJER-2026-0158',
    title: 'Corrosion Behaviour of Mild Steel in Niger Delta Produced Water',
    section: 'Metallurgical & Materials',
    status: 'reviewer_search',
    correspondingAuthor: 'T. Adeyemi',
    authorCount: 3,
    handlingEditor: 'A. Okonkwo',
    round: 1,
    submittedAt: '2026-08-21',
    daysInStatus: 23,
    similarityPercent: 11,
    blinding: 'double_blind',
    hasOverdueReview: false,
    reviewers: [
      { id: 'r7', displayName: 'Reviewer 1', status: 'declined', dueAt: '2026-09-18' },
      { id: 'r8', displayName: 'Reviewer 2', status: 'expired', dueAt: '2026-09-18' },
    ],
  },
  {
    id: 'm4',
    reference: 'UJER-2026-0163',
    title: 'Optimisation of Biogas Yield from Co-Digested Market Waste in Lagos State',
    section: 'Chemical & Petroleum',
    status: 'submitted',
    correspondingAuthor: 'F. Oyelaran',
    authorCount: 5,
    handlingEditor: null,
    round: 0,
    submittedAt: '2026-09-11',
    daysInStatus: 2,
    similarityPercent: 34,
    blinding: 'double_blind',
    hasOverdueReview: false,
    reviewers: [],
  },
  {
    id: 'm5',
    reference: 'UJER-2026-0122',
    title: 'A Finite Element Study of Pile-Raft Foundations on Lagos Coastal Sands',
    section: 'Civil & Structural',
    status: 'revision_requested',
    correspondingAuthor: 'K. Bassey',
    authorCount: 2,
    handlingEditor: 'A. Okonkwo',
    round: 1,
    submittedAt: '2026-05-14',
    daysInStatus: 17,
    similarityPercent: 6,
    blinding: 'double_blind',
    hasOverdueReview: false,
    reviewers: [
      { id: 'r9', displayName: 'Reviewer 1', status: 'submitted', dueAt: '2026-07-30', recommendation: 'major_revision' },
      { id: 'r10', displayName: 'Reviewer 2', status: 'submitted', dueAt: '2026-07-30', recommendation: 'major_revision' },
    ],
  },
  {
    id: 'm6',
    reference: 'UJER-2026-0139',
    title: 'Traffic Flow Characterisation on the Lagos–Ibadan Expressway Corridor After Rehabilitation',
    section: 'Civil & Structural',
    status: 'resubmitted',
    correspondingAuthor: 'M. Ogundipe',
    authorCount: 3,
    handlingEditor: 'A. Okonkwo',
    round: 2,
    submittedAt: '2026-06-08',
    daysInStatus: 4,
    similarityPercent: 9,
    blinding: 'double_blind',
    hasOverdueReview: false,
    reviewers: [
      { id: 'r11', displayName: 'Reviewer 1', status: 'accepted', dueAt: '2026-09-26' },
      { id: 'r12', displayName: 'Reviewer 2', status: 'invited', dueAt: '2026-09-26' },
    ],
  },
  {
    id: 'm7',
    reference: 'UJER-2026-0118',
    title: 'Thermal Performance of Phase-Change Material Walls in Humid Tropical Climates',
    section: 'Mechanical',
    status: 'accepted',
    correspondingAuthor: 'S. Aluko',
    authorCount: 2,
    handlingEditor: 'A. Okonkwo',
    round: 2,
    submittedAt: '2026-04-27',
    daysInStatus: 6,
    similarityPercent: 7,
    blinding: 'double_blind',
    hasOverdueReview: false,
    reviewers: [
      { id: 'r13', displayName: 'Reviewer 1', status: 'submitted', dueAt: '2026-08-20', recommendation: 'accept' },
      { id: 'r14', displayName: 'Reviewer 2', status: 'submitted', dueAt: '2026-08-20', recommendation: 'minor_revision' },
    ],
  },
  {
    id: 'm8',
    reference: 'UJER-2026-0160',
    title: 'Machine Vision Inspection of Weld Defects in Locally Fabricated Pressure Vessels',
    section: 'Mechanical',
    status: 'desk_review',
    correspondingAuthor: 'H. Danjuma',
    authorCount: 4,
    handlingEditor: null,
    round: 0,
    submittedAt: '2026-09-06',
    daysInStatus: 7,
    similarityPercent: 19,
    blinding: 'double_blind',
    hasOverdueReview: false,
    reviewers: [],
  },
]
