services:
  postgres:
    image: postgres:16-alpine
    container_name: ujer-postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      POSTGRES_DB: unilag_journal
    volumes:
      - ujer_pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d unilag_journal"]
      interval: 2s
      timeout: 5s
      retries: 30

volumes:
  ujer_pg:
