import { createHash } from 'node:crypto'
import { mkdir, readFile, unlink, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { and, eq } from 'drizzle-orm'
import { z } from 'zod'
import type { Tx } from '@/db/client'
import { resolvePolicy, type JournalPolicy } from '@/db/policy'
import { fileKind, files, journals, manuscripts, sections } from '@/db/schema'
import { Errors } from '@/server/errors'
import { audit } from '@/server/audit'
import { enqueue } from '@/server/jobs/service'

const ROOT = path.join(process.cwd(), '.data', 'objects')

/**
 * Local disk for development. The storage key is generated by us
 * (`journal/manuscript/file`), never taken from the uploaded filename.
 * Production should swap this for object storage; the key format stays.
 */
async function putObject(key: string, body: Buffer) {
  const full = path.resolve(ROOT, key)
  if (!full.startsWith(path.resolve(ROOT))) throw Errors.badRequest('Invalid storage key')
  await mkdir(path.dirname(full), { recursive: true })
  await writeFile(full, body)
}

export async function removeStoredFile(key: string) {
  const full = path.resolve(ROOT, key)
  if (!full.startsWith(path.resolve(ROOT))) return
  await unlink(full).catch(() => {})
}

async function getObject(key: string) {
  const full = path.resolve(ROOT, key)
  if (!full.startsWith(path.resolve(ROOT))) throw Errors.badRequest('Invalid storage key')
  return readFile(full)
}

export const fileKindInput = z.enum(fileKind.enumValues)

const REVIEWER_KINDS = new Set(['manuscript_anonymised', 'review_pdf', 'figure', 'supplementary'])
const AUTHOR_KINDS = new Set([
  'manuscript',
  'figure',
  'supplementary',
  'cover_letter',
  'response_to_reviewers',
  'galley_pdf',
  'galley_xml',
])

function policyFor(manuscript: typeof manuscripts.$inferSelect, journal: typeof journals.$inferSelect, section: typeof sections.$inferSelect | null): JournalPolicy {
  if (manuscript.policySnapshot) return manuscript.policySnapshot.policy
  return resolvePolicy(journal.policy, section?.policyOverrides ?? null)
}

export async function registerUpload(
  tx: Tx,
  input: {
    journal: typeof journals.$inferSelect
    manuscript: typeof manuscripts.$inferSelect
    section: typeof sections.$inferSelect | null
    actorId: string
    kind: z.infer<typeof fileKindInput>
    originalName: string
    mimeType: string
    bytes: Buffer
  },
) {
  const policy = policyFor(input.manuscript, input.journal, input.section)
  const maxBytes = policy.submission.maxFileSizeMb * 1024 * 1024
  if (input.bytes.byteLength > maxBytes) {
    throw Errors.badRequest(`File is larger than ${policy.submission.maxFileSizeMb} MB`)
  }
  const extension = path.extname(input.originalName).toLowerCase()
  if (extension && !policy.submission.acceptedFileTypes.includes(extension)) {
    throw Errors.badRequest(`This journal does not accept ${extension} files`)
  }

  const id = crypto.randomUUID()
  const key = `${input.journal.id}/${input.manuscript.id}/${id}`
  const checksum = createHash('sha256').update(input.bytes).digest('hex')
  await putObject(key, input.bytes)

  const [row] = await tx
    .insert(files)
    .values({
      id,
      journalId: input.journal.id,
      manuscriptId: input.manuscript.id,
      kind: input.kind,
      storageKey: key,
      originalName: path.basename(input.originalName),
      mimeType: input.mimeType || 'application/octet-stream',
      sizeBytes: input.bytes.byteLength,
      checksumSha256: checksum,
      isMetadataScrubbed: false,
      uploadedById: input.actorId,
    })
    .returning()

  await enqueue(tx, {
    journalId: input.journal.id,
    type: 'scrub_metadata',
    payload: { fileId: row.id, manuscriptId: input.manuscript.id },
  })
  return row
}

/**
 * Reviewers receive only a scrubbed anonymised copy or a scrubbed figure.
 * The original manuscript file is never in this set. A false
 * `isMetadataScrubbed` is a hard stop, not a warning.
 */
export async function readForReviewer(tx: Tx, fileId: string, journalId: string) {
  const [file] = await tx
    .select()
    .from(files)
    .where(and(eq(files.id, fileId), eq(files.journalId, journalId)))
    .limit(1)
  if (!file) throw Errors.notFound('File')
  if (!REVIEWER_KINDS.has(file.kind)) throw Errors.forbidden('Reviewers are not given this file')
  if (!file.isMetadataScrubbed) {
    throw Errors.conflict('This file has not been scrubbed of author metadata yet')
  }
  const bytes = await getObject(file.storageKey)
  return { file, bytes }
}

export async function readForStaff(tx: Tx, fileId: string, journalId: string) {
  const [file] = await tx
    .select()
    .from(files)
    .where(and(eq(files.id, fileId), eq(files.journalId, journalId)))
    .limit(1)
  if (!file) throw Errors.notFound('File')
  const bytes = await getObject(file.storageKey)
  return { file, bytes }
}

export async function readForAuthor(tx: Tx, fileId: string, journalId: string) {
  const [file] = await tx
    .select()
    .from(files)
    .where(and(eq(files.id, fileId), eq(files.journalId, journalId)))
    .limit(1)
  if (!file) throw Errors.notFound('File')
  if (!AUTHOR_KINDS.has(file.kind)) throw Errors.forbidden('This file is not part of the author record')
  const bytes = await getObject(file.storageKey)
  return { file, bytes }
}

export async function markScrubbed(tx: Tx, fileId: string, journalId: string, actorId: string, ipAddress: string | null) {
  const [file] = await tx.select().from(files).where(and(eq(files.id, fileId), eq(files.journalId, journalId))).limit(1)
  if (!file) throw Errors.notFound('File')
  if (!REVIEWER_KINDS.has(file.kind)) {
    throw Errors.badRequest('Only a reviewer-facing copy can be marked scrubbed. The original manuscript is never served to reviewers.')
  }
  const [updated] = await tx.update(files).set({ isMetadataScrubbed: true }).where(eq(files.id, file.id)).returning()
  await audit(tx, {
    journalId,
    actorId,
    action: 'file.marked_scrubbed',
    entityType: 'file',
    entityId: file.id,
    metadata: { kind: file.kind },
    ipAddress,
  })
  return updated
}

export function fileResponse(file: { mimeType: string; originalName: string }, bytes: Buffer, inline = false) {
  const name = file.originalName.replaceAll('"', '')
  return new Response(new Uint8Array(bytes), {
    headers: {
      'Content-Type': file.mimeType || 'application/octet-stream',
      'Content-Disposition': `${inline ? 'inline' : 'attachment'}; filename="${name}"`,
    },
  })
}

/** The file attached to this review assignment. The token is the only credential. */
export async function readAssignedManuscript(tx: Tx, fileId: string, journalId: string, manuscriptId: string) {
  const [file] = await tx
    .select()
    .from(files)
    .where(and(eq(files.id, fileId), eq(files.journalId, journalId), eq(files.manuscriptId, manuscriptId)))
    .limit(1)
  if (!file) throw Errors.notFound('File')
  if (!['manuscript', 'manuscript_anonymised', 'figure', 'supplementary', 'reviewer_attachment', 'review_pdf'].includes(file.kind)) {
    throw Errors.forbidden('Reviewers are not given this file')
  }
  const bytes = await getObject(file.storageKey)
  return { file, bytes }
}
